// <auto-generated />
namespace Sto.NinoRMS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update032620 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update032620));
        
        string IMigrationMetadata.Id
        {
            get { return "202003261415421_update-032620"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
