// <auto-generated />
namespace Sto.NinoRMS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateResidency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateResidency));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141517346_updateResidency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
